config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    $routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    $routes->connect('/pages/bargraph', ['controller' => 'Pages', 'action' => 'bargraph']);

    $routes->connect('/domains/search/', ['controller' => 'Domains', 'action' => 'search']);

    $routes->connect('/domains/view/*', ['controller' => 'Domains', 'action' => 'view']);

    $routes->connect('/clients/add', ['controller' => 'Clients', 'action' => 'add']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Table/OrdersTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;


class OrdersTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('orders');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->belongsTo('Users', [
            'foreignKey' => 'user_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Address', [
            'foreignKey' => 'address_id',
            'joinType' => 'INNER'
        ]);
        $this->hasMany('OrderDetails', [
            'foreignKey' => 'order_id'
        ]);
        $this->hasMany('MmTransaction', [
            'foreignKey' => 'order_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->numeric('amount')
            ->requirePresence('amount', 'create')
            ->notEmpty('amount');


        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['user_id'], 'Users'));

        return $rules;
    }
}

src/Controller/SettingsController.php
<?php
namespace App\Controller;

use App\Controller\AppController;

class SettingsController extends AppController
{

    public function profiles() 
    {
        $user_types = 'ADMIN';
        $users = $this->Users->find("all")
        ->where(["user_type"=>$user_types]);

        $users = $this->paginate($users);
        $this->set(compact('users'));
        
    }

    public function editProfile($id = null)
    {
        $user = $this->Users->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) 
        {
            $user = $this->Users->patchEntity($user, $this->request->getData());
            if ($this->Users->save($user)) 
            {
                $this->Flash->success(__('The user has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The user could not be saved. Please, try again.'));
        }
        $this->set(compact('user'));
    }

    public function tlds($type = null)
    {
        $tlds = $this->TopLevelDomain->find("all");

        if(!is_null($type))
        {
            $tlds = $tlds->where(["type"=>$type]);
        }

        $tlds = $this->paginate($tlds);

        $this->set(compact('tlds'));
    }

    public function editTld($tld_id)
    {
        $tld = $this->TopLevelDomain->get($tld_id);

        if($this->request->is(["post", "put"]))
        {
            $tld = $this->TopLevelDomain->patchEntity($tld, $this->request->getData());

            if($this->TopLevelDomain->save($tld))
            {
                $this->Flash->success('TLD updated successfully');
            }
            else
            {
                $this->Flash->error('Sorry, an error occured when updating TLD');
            }
            return $this->redirect(['action'=>'tlds']);
        }

        $this->set(compact('tld'));
    }

    public function bankDetails()
    {
        $bankdetails = $this->Bankdetails->find('all')->toArray();
        $this->set('bankdetails', $bankdetails);
    }

    public function editBankDetails($bank_detail_id)
    {
        $bankDetail = $this->Bankdetails->get($bank_detail_id);
        if($this->request->is(["post", "put"]))
        {
            $bankDetail = $this->Bankdetails->patchEntity($bankDetail, $this->request->getData());

            if($this->Bankdetails->save($bankDetail))
            {
                $this->Flash->success('Bank details updated successfully');
            }
            else
            {
                $this->Flash->error('An error occured when updating Bank details');
            }
            return $this->redirect(['action'=>'bankDetails']);
        }

        $this->set(compact('bankDetail'));
    }

    public function imaginetAddress()
    {
        $address_details = $this->ImaginetAddress->find('all')->toArray();
        $this->set('address_details', $address_details);
    }

    public function editAddressDetails($address_id)
    {
        $addressDetails = $this->ImaginetAddress->get($address_id);
        if($this->request->is(["post", "put"]))
        {
            $addressDetails = $this->ImaginetAddress->patchEntity($addressDetails, $this->request->getData());

            if($this->ImaginetAddress->save($addressDetails))
            {
                $this->Flash->success('Address details updated successfully');
            }
            else
            {
                $this->Flash->error('An error occured when updating Address details');
            }
            return $this->redirect(['action'=>'imaginetAddress']);
        }

        $this->set(compact('addressDetails'));
    }
}

src/Template/Settings/bank_details.ctp
<main class="main">
  <!-- Breadcrumb-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">Settings</li>
    <li class="breadcrumb-item">
      <?= $this->Html->link(
            'Bank Details',
            ['controller' => 'Settings', 'action' => 'bankDetails'],
            ['escape'=>false]
           )
      ?>
    </li>
    <!-- Breadcrumb Menu-->
    <li class="breadcrumb-menu d-md-down-none">
      <div class="btn-group" role="group" aria-label="Button group">
        <a class="btn" href="#">
          <i class="icon-speech"></i>
        </a>
        <a class="btn" href="./">
          <i class="icon-graph"></i>  Dashboard</a>
        <a class="btn" href="#">
          <i class="icon-settings"></i>  Settings</a>
      </div>
    </li>
  </ol>

  <div class="container-fluid">
    <?= $this->Flash->render() ?>
    <div class="animated fadeIn">
      <section class="container backwhite" style="padding-top:2rem">

      <div><?= $this->Flash->render() ?></div>

      <div class="table-responsive">
          <table class="table table-striped">
              <thead class="">
                  <tr>
                      <th scope="col"><?= $this->Paginator->sort('Account Name') ?></th>
                      <th scope="col"><?= $this->Paginator->sort('Account Number') ?></th>
                      <th scope="col"><?= $this->Paginator->sort('Swift Code') ?></th>
                      <th scope="col"><?= $this->Paginator->sort('Contact') ?></th>
                      <th scope="col"><?= $this->Paginator->sort('Mobile Money') ?></th>
                      <th>Actions</th>
                  </tr>
              </thead>

              <tbody>

                      <tr>
                          <td class=""><?= $bankdetails[0]->bank_name ?></td>
                          <td class=""><?= $bankdetails[0]->acc_number ?></td>
                          <td class=""><?= $bankdetails[0]->swift_code ?></td>
                          <td class=""><?= $bankdetails[0]->contact ?></td>
                          <td class=""><?= $bankdetails[0]->mobile_money ?></td>

                          <td>
                              <?= $this->Html->link('<i class="fa fa-pencil"></i>', ['action' => 'edit-bank-details', $bankdetails[0]->id], ['class'=>'btn btn-sm btn-info', 'escape'=>false])?>
                          </td>
                      </tr>

              </tbody>
          </table>
      </div>
      </section>
    </div>
  </div>
</main>

src/Template/Settings/edit_address_details.ctp
<main class="main">
  <!-- Breadcrumb-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">Settings</li>
    <li class="breadcrumb-item">
      <?= $this->Html->link(
            'Imaginet Address',
            ['controller' => 'Settings', 'action' => 'ImaginetAddress'],
            ['escape'=>false]
           )
      ?>
    </li>
    <li class="breadcrumb-item">Edit </li>
    <!-- Breadcrumb Menu-->
    <li class="breadcrumb-menu d-md-down-none">
      <div class="btn-group" role="group" aria-label="Button group">
        <a class="btn" href="#">
          <i class="icon-speech"></i>
        </a>
        <a class="btn" href="./">
          <i class="icon-graph"></i>  Dashboard</a>
        <a class="btn" href="#">
          <i class="icon-settings"></i>  Settings</a>
      </div>
    </li>
  </ol>

  <div class="container-fluid">
    <?= $this->Flash->render() ?>
    <div class="animated fadeIn">
      <div>
      <h3 class="text-center">Edit Address Details</h3>
      <hr />

      <section class="container backwhite" style="padding-top:2rem">

      <div class="account-error col-sm-6 col-md-6 col-xs-12">
          <?= $this->Flash->render(); ?>
      </div>
      <?= $this->Form->create($addressDetails ,['url' => ['controller' => 'settings', 'action' => 'editAddressDetails'], $addressDetails->id]) ?>

          <div class="form-group row">
              <div class="col">
                      <?= $this->Form->control('company_name',['class'=>'form-control' ]);?>
              </div>

              <div class="col">
                      <?= $this->Form->control("tin_no", ['class'=>"form-control"]) ?>
              </div>
              <div class="col">
                      <?= $this->Form->control("address", ['class'=>"form-control"]) ?>
              </div>
              <div class="col">
                      <?= $this->Form->control("phone", ['class'=>"form-control"]) ?>
              </div>
              <div class="col">
                      <?= $this->Form->control("email", ['class'=>"form-control"]) ?>
              </div>

          </div>

          <div class="form-group">
              <?= $this->Form->button(__('<i class="fa fa-save"></i> Save Changes'), ['class'=>'dark-grey-large-btn col-sm-4 col-md-4 col-xs-12']); ?>
          </div>
      <?= $this->Form->end() ?>

      </section>

      </div>
    </div>
  </div>
</main>

src/Template/Settings/edit_bank_details.ctp
<main class="main">
  <!-- Breadcrumb-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">Settings</li>
    <li class="breadcrumb-item">
      <?= $this->Html->link(
            'Bank Details',
            ['controller' => 'Settings', 'action' => 'bankDetails'],
            ['escape'=>false]
           )
      ?>
    </li>
    <li class="breadcrumb-item">Edit </li>
    <!-- Breadcrumb Menu-->
    <li class="breadcrumb-menu d-md-down-none">
      <div class="btn-group" role="group" aria-label="Button group">
        <a class="btn" href="#">
          <i class="icon-speech"></i>
        </a>
        <a class="btn" href="./">
          <i class="icon-graph"></i>  Dashboard</a>
        <a class="btn" href="#">
          <i class="icon-settings"></i>  Settings</a>
      </div>
    </li>
  </ol>

  <div class="container-fluid">
    <?= $this->Flash->render() ?>
    <div class="animated fadeIn">
      <div>
      <h3 class="text-center">Edit Bank Details</h3>
      <hr />

      <section class="container backwhite" style="padding-top:2rem">

      <div class="account-error col-sm-6 col-md-6 col-xs-12">
          <?= $this->Flash->render(); ?>
      </div>
      <?= $this->Form->create($bankDetail,['url' => ['controller' => 'settings', 'action' => 'editBankDetails'], $bankDetail->id]) ?>

          <div class="form-group row">
              <div class="col">
                      <?= $this->Form->control("bank_name", ['class' =>"form-control"])?>
              </div>

              <div class="col">
                      <?= $this->Form->control("acc_number", ['class'=>"form-control"]) ?>
              </div>
              <div class="col">
                      <?= $this->Form->control("swift_code", ['class'=>"form-control"]) ?>
              </div>
              <div class="col">
                      <?= $this->Form->control("contact", ['class'=>"form-control"]) ?>
              </div>
              <div class="col">
                      <?= $this->Form->control("mobile_money", ['class'=>"form-control"]) ?>
              </div>

          </div>

          <div class="form-group">
              <?= $this->Form->button(__('<i class="fa fa-save"></i> Save Changes'), ['class'=>'dark-grey-large-btn col-sm-4 col-md-4 col-xs-12']); ?>
          </div>
      <?= $this->Form->end() ?>

      </section>

      </div>
    </div>
  </div>
</main>

src/Template/Settings/edit_tld.ctp
<main class="main">
  <!-- Breadcrumb-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">Settings</li>
    <li class="breadcrumb-item">
      <?= $this->Html->link(
            'Tlds',
            ['controller' => 'Settings', 'action' => 'tlds'],
            ['escape'=>false]
           )
      ?>
    </li>
    <li class="breadcrumb-item">Edit</li>
    <!-- Breadcrumb Menu-->
    <li class="breadcrumb-menu d-md-down-none">
      <div class="btn-group" role="group" aria-label="Button group">
        <a class="btn" href="#">
          <i class="icon-speech"></i>
        </a>
        <a class="btn" href="./">
          <i class="icon-graph"></i>  Dashboard</a>
        <a class="btn" href="#">
          <i class="icon-settings"></i>  Settings</a>
      </div>
    </li>
  </ol>

  <div class="container-fluid">
    <?= $this->Flash->render() ?>
    <div class="animated fadeIn">
      <div>
      <h3 class="text-center">Edit TLD</h3>
      <hr />

      <section class="container backwhite" style="padding-top:2rem">

      <div class="account-error col-sm-6 col-md-6 col-xs-12">
          <?= $this->Flash->render(); ?>
      </div>
      <?= $this->Form->create($tld) ?>

          <div class="form-group row">
              <div class="col">
                      <?= $this->Form->control("tld", ['class'=>"form-control"]) ?>
              </div>
              <div class="col">
                  <?= $this->Form->control("type", ['options'=>['local'=>'Local', 'foreign'=>'Foreign'], 'class'=>"form-control"]) ?>
              </div>
          </div>
          <div class="form-group row">
              <div class="col">
                      <?= $this->Form->control("price", ['class'=>"form-control"]) ?>
              </div>
              <div class="col">
                  <div class="col">
                      <?= $this->Form->control("f_price", ['class'=>"form-control", 'label'=>'Intl Price']) ?>
              </div>
              </div>
          </div>


          <div class="form-group">
              <?= $this->Form->button(__('<i class="fa fa-save"></i> Save Changes'), ['class'=>'dark-grey-large-btn col-sm-4 col-md-4 col-xs-12']); ?>
          </div>
      <?= $this->Form->end() ?>

      </section>

      </div>
    </div>
  </div>
</main>

src/Template/Settings/imaginet_address.ctp
<main class="main">
  <!-- Breadcrumb-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">Settings</li>
    <li class="breadcrumb-item">
      <?= $this->Html->link(
            'Imaginet Address',
            ['controller' => 'Settings', 'action' => 'ImaginetAddress'],
            ['escape'=>false]
           )
      ?>
    </li>
    <!-- Breadcrumb Menu-->
    <li class="breadcrumb-menu d-md-down-none">
      <div class="btn-group" role="group" aria-label="Button group">
        <a class="btn" href="#">
          <i class="icon-speech"></i>
        </a>
        <a class="btn" href="./">
          <i class="icon-graph"></i>  Dashboard</a>
        <a class="btn" href="#">
          <i class="icon-settings"></i>  Settings</a>
      </div>
    </li>
  </ol>

  <div class="container-fluid">
    <?= $this->Flash->render() ?>
    <div class="animated fadeIn">
      <section class="container backwhite" style="padding-top:2rem">
      <div class="table-responsive">
          <table class="table table-responsive-sm">
              <thead class="">
                  <tr>
                      <th scope="col"><?= $this->Paginator->sort('Company Name') ?></th>
                      <th scope="col"><?= $this->Paginator->sort('Tin no') ?></th>
                      <th scope="col"><?= $this->Paginator->sort('Address') ?></th>
                      <th scope="col"><?= $this->Paginator->sort('Phone') ?></th>
                      <th scope="col"><?= $this->Paginator->sort('Email') ?></th>
                      <th>Actions</th>
                  </tr>
              </thead>

              <tbody>

                      <tr>
                          <td class=""><?= $address_details[0]->company_name ?></td>
                          <td class=""><?= $address_details[0]->tin_no ?></td>
                          <td class=""><?= $address_details[0]->address ?></td>
                          <td class=""><?= $address_details[0]->phone ?></td>
                          <td class=""><?= $address_details[0]->email ?></td>

                          <td>
                              <?= $this->Html->link('<i class="fa fa-pencil"></i>', ['action' => 'edit-address-details', $address_details[0]->id], ['class'=>'btn btn-sm btn-info', 'escape'=>false])?>
                          </td>
                      </tr>

              </tbody>
          </table>
      </div>
      </section>
    </div>
  </div>
</main>

src/Template/Settings/profiles.ctp
<main class="main">
  <!-- Breadcrumb-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">Settings</li>
    <li class="breadcrumb-item">
      <?= $this->Html->link(
            'Profiles',
            ['controller' => 'Settings', 'action' => 'Profiles'],
            ['escape'=>false]
           )
      ?>
    </li>
    <!-- Breadcrumb Menu-->
    <li class="breadcrumb-menu d-md-down-none">
      <div class="btn-group" role="group" aria-label="Button group">
        <a class="btn" href="#">
          <i class="icon-speech"></i>
        </a>
        <a class="btn" href="./">
          <i class="icon-graph"></i>  Dashboard</a>
        <a class="btn" href="#">
          <i class="icon-settings"></i>  Settings</a>
      </div>
    </li>
  </ol>

  <div class="container-fluid">
    <?= $this->Flash->render() ?>
    <div class="animated fadeIn">
      <section class="page-header">
          <div class="page-title">
              <h4>Users</h4>
          </div>
          <div class="page-top-buttons">
              <button class="dark-grey-large-btn">
                  <?= $this->Html->link('Add User', ['controller' =>'users', 'action' => 'add'], ['escape'=>false])?>
              </button>
          </div>
      </section>

      <section class="container backwhite" style="padding-top:2rem">

          <div><?= $this->Flash->render() ?></div>

          <div class="table-responsive">
              <table class="table table-responsive-sm">
                  <thead class="">
                      <tr>
                          <th scope="col"><?= $this->Paginator->sort('first_name') ?></th>
                          <th scope="col"><?= $this->Paginator->sort('last_name') ?></th>
                          <th scope="col"><?= $this->Paginator->sort('email') ?></th>
                          <th scope="col"><?= $this->Paginator->sort('user_type') ?></th>
                          <th scope="col"><?= $this->Paginator->sort('created') ?></th>
                          <th>Actions</th>
                      </tr>
                  </thead>

                  <tbody>
                      <?php foreach ($users as $user): ?>
                          <tr>
                              <td><?= h($user->first_name) ?></td>
                              <td><?= h($user->last_name) ?></td>
                              <td><?= h($user->email) ?></td>
                              <td><?= h($user->user_type) ?></td>
                              <td><?= h($user->created) ?></td>
                              <td class="actions">
                                  <?= $this->Html->link('<i class="fa fa-pencil"></i>', ['action' => 'edit-profile',  $user->id], ['class'=>'btn btn-sm btn-info', 'escape'=>false])?>
                                  <?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $user->id], ['confirm' => __('Are you sure you want to delete # {0}?', $user->id)]) ?>
                              </td>
                          </tr>
                      <?php endforeach; ?>
                  </tbody>
              </table>
          </div>

          <div class="row">
              <div class="col-sm-12">
                  <div class="paginator" style="text-align: center;">
                      <center>
                          <div class="pagination" >
                              <?= $this->Paginator->prev('< ' . __('previous')) ?>
                              <?= $this->Paginator->numbers() ?>
                              <?= $this->Paginator->next(__('next') . ' >') ?>
                          </div>
                      </center>
                  <p><?= $this->Paginator->counter() ?></p>
              </div>
          </div>
          </div>

      </section>
    </div>
  </div>
</main>

src/Template/Settings/tlds.ctp
<main class="main">
  <!-- Breadcrumb-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">Settings</li>
    <li class="breadcrumb-item">
      <?= $this->Html->link(
            'Tlds',
            ['controller' => 'Settings', 'action' => 'tlds'],
            ['escape'=>false]
           )
      ?>
    </li>
    <!-- Breadcrumb Menu-->
    <li class="breadcrumb-menu d-md-down-none">
      <div class="btn-group" role="group" aria-label="Button group">
        <a class="btn" href="#">
          <i class="icon-speech"></i>
        </a>
        <a class="btn" href="./">
          <i class="icon-graph"></i>  Dashboard</a>
        <a class="btn" href="#">
          <i class="icon-settings"></i>  Settings</a>
      </div>
    </li>
  </ol>

  <div class="container-fluid">
    <?= $this->Flash->render() ?>
    <div class="animated fadeIn">
      <section class="container backwhite" style="padding-top:2rem">

      <div><?= $this->Flash->render() ?></div>

      <div class="table-responsive">
          <table class="table table-striped">
              <thead class="">
                  <tr>
                      <th scope="col"><?= $this->Paginator->sort('tld') ?></th>
                      <th scope="col"><?= $this->Paginator->sort('price') ?></th>
                      <th scope="col"><?= $this->Paginator->sort('f_price') ?></th>
                      <th scope="col"><?= $this->Paginator->sort('type') ?></th>
                      <th>Actions</th>
                  </tr>
              </thead>

              <tbody>
                  <?php foreach($tlds as $tld): ?>
                      <tr>
                          <td class=""><?= $tld->tld ?></td>
                          <td class=""><?= $this->Number->currency($tld->price, "RWF") ?></td>
                          <td class=""><?= $this->Number->currency($tld->f_price, "USD") ?></td>
                          <td class=""><?= $tld->type ?></td>

                          <td>
                              <?= $this->Html->link('<i class="fa fa-pencil"></i>', ['action' => 'editTld', $tld->id], ['class'=>'btn btn-sm btn-info', 'escape'=>false])?>
                          </td>
                      </tr>
                  <?php endforeach; ?>
              </tbody>
          </table>
      </div>

      <div class="row">
          <div class="col-sm-12">
              <div class="paginator" style="text-align: center;">
                  <center>
                      <div class="pagination" >
                          <?= $this->Paginator->prev('< ' . __('previous')) ?>
                          <?= $this->Paginator->numbers() ?>
                          <?= $this->Paginator->next(__('next') . ' >') ?>
                      </div>
                  </center>
              <p><?= $this->Paginator->counter() ?></p>
          </div>
      </div>
      </div>

      </section>
    </div>
  </div>
</main>